"""Add image and video fields to posts

Revision ID: 5dd03571aab7
Revises: a943fc02885e
Create Date: 2024-11-15 23:27:28.083454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd03571aab7'
down_revision = 'a943fc02885e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('image_content_type', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('video_data', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('video_content_type', sa.String(length=50), nullable=True))
    op.drop_column('posts', 'image_path')
    op.drop_column('posts', 'video_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_path', sa.VARCHAR(length=255), nullable=True))
    op.add_column('posts', sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('posts', 'video_content_type')
    op.drop_column('posts', 'video_data')
    op.drop_column('posts', 'image_content_type')
    op.drop_column('posts', 'image_data')
    # ### end Alembic commands ###
